# Data Mining Project

## XYZ Sports Company

**Group elements:**
* Devora Cavaleiro (20230974);
* XX (XXX);
* XX (XXX).

### Data preprocessing

#### Importing the librabries

In [16]:
import numpy as np
import matplotlib as plt
import pandas as pd

#### Importing the dataset

In [17]:
df = pd.read_csv("XYZ_sports_dataset.csv", sep=";")
df

ID  Age  Gender  Income EnrollmentStart EnrollmentFinish  \
0      10000   60  Female  5500.0      2019-09-03       2019-10-31   
1      10001   29  Female  2630.0      2014-08-12       2015-09-14   
2      10002   23    Male  1980.0      2017-05-02       2017-06-01   
3      10003    9    Male     0.0      2018-09-05       2019-02-12   
4      10004   35    Male  4320.0      2016-04-20       2018-06-07   
...      ...  ...     ...     ...             ...              ...   
14937  24937   14    Male     0.0      2016-09-08       2016-09-08   
14938  24938   39    Male     NaN      2015-09-17       2016-06-04   
14939  24939   20    Male  1810.0      2017-03-01       2017-03-31   
14940  24940   55    Male  4800.0      2018-03-01       2018-03-01   
14941  24941   32  Female  3700.0      2016-04-01       2019-06-11   

      LastPeriodStart LastPeriodFinish DateLastVisit  DaysWithoutFrequency  \
0          2019-07-01       2019-12-31    2019-10-30                     1   
1          2015-01-01       2015-12-31    2015-07-16                    60   
2          2017-01-01       2017-06-30    2017-05-25                     7   
3          2018-07-01       2019-06-30    2019-01-21                    22   
4          2018-01-01       2018-06-30    2017-11-09                   210   
...               ...              ...           ...                   ...   
14937      2019-07-01       2019-12-31    2019-10-29                     2   
14938      2016-01-01       2016-06-30    2016-04-27                    38   
14939      2017-01-01       2017-06-30    2017-03-29                     2   
14940      2019-07-01       2019-12-31    2019-10-28                     3   
14941      2019-01-01       2019-06-30    2019-05-28                    14   

       ...  OtherActivities  NumberOfFrequencies  AttendedClasses  \
0      ...              0.0                  9.0                7   
1      ...              0.0                 23.0                1   
2      ...              0.0                  6.0                0   
3      ...              0.0                 20.0                2   
4      ...              NaN                 41.0                0   
...    ...              ...                  ...              ...   
14937  ...              0.0                112.0               96   
14938  ...              0.0                 57.0                0   
14939  ...              0.0                  6.0                0   
14940  ...              0.0                185.0              155   
14941  ...              0.0                169.0                1   

       AllowedWeeklyVisitsBySLA  AllowedNumberOfVisitsBySLA  \
0                           NaN                        6.28   
1                           2.0                       17.42   
2                           7.0                       30.03   
3                           2.0                       17.72   
4                           7.0                       60.97   
...                         ...                         ...   
14937                       4.0                       34.84   
14938                       7.0                       60.97   
14939                       7.0                       30.03   
14940                       3.0                       15.87   
14941                       7.0                       60.97   

       RealNumberOfVisits  NumberOfRenewals  HasReferences  \
0                       2                 0            0.0   
1                       1                 2            0.0   
2                       6                 0            0.0   
3                       3                 0            0.0   
4                       0                 3            0.0   
...                   ...               ...            ...   
14937                   8                 3            0.0   
14938                   3                 0            0.0   
14939                   8                 0            0.0   
14940                   7 

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14942 entries, 0 to 14941
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   ID                          14942 non-null  int64  
 1   Age                         14942 non-null  int64  
 2   Gender                      14942 non-null  object 
 3   Income                      14447 non-null  float64
 4   EnrollmentStart             14942 non-null  object 
 5   EnrollmentFinish            14942 non-null  object 
 6   LastPeriodStart             14942 non-null  object 
 7   LastPeriodFinish            14942 non-null  object 
 8   DateLastVisit               14942 non-null  object 
 9   DaysWithoutFrequency        14942 non-null  int64  
 10  LifetimeValue               14942 non-null  float64
 11  UseByTime                   14942 non-null  int64  
 12  AthleticsActivities         14906 non-null  float64
 13  WaterActivities             149

#### Matrix of features

In [19]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [20]:
X

array([[10000, 60, 'Female', ..., 0, 0.0, 0],
       [10001, 29, 'Female', ..., 2, 0.0, 0],
       [10002, 23, 'Male', ..., 0, 0.0, 0],
       ...,
       [24939, 20, 'Male', ..., 0, 0.0, 0],
       [24940, 55, 'Male', ..., 2, 0.0, 0],
       [24941, 32, 'Female', ..., 4, 0.0, 0]], dtype=object)

In [21]:
y

array([0, 1, 1, ..., 1, 0, 1], dtype=int64)

#### Missing data

In [22]:
# count of missing values
df.isna().sum()

ID                              0
Age                             0
Gender                          0
Income                        495
EnrollmentStart                 0
EnrollmentFinish                0
LastPeriodStart                 0
LastPeriodFinish                0
DateLastVisit                   0
DaysWithoutFrequency            0
LifetimeValue                   0
UseByTime                       0
AthleticsActivities            36
WaterActivities                37
FitnessActivities              35
DanceActivities                36
TeamActivities                 35
RacketActivities               37
CombatActivities               33
NatureActivities               47
SpecialActivities              44
OtherActivities                35
NumberOfFrequencies            26
AttendedClasses                 0
AllowedWeeklyVisitsBySLA      535
AllowedNumberOfVisitsBySLA      0
RealNumberOfVisits              0
NumberOfRenewals                0
HasReferences                  12
NumberOfRefere

#### Check descriptive statistics

In [23]:
df.describe(include="all").T
# DaysWithoutFrequency, LifetimeValue, NumberOfFrequencies, AttendedClasses has outliers

count unique         top  freq         mean  \
ID                          14942.0    NaN         NaN   NaN      17470.5   
Age                         14942.0    NaN         NaN   NaN    26.015794   
Gender                        14942      2      Female  8931          NaN   
Income                      14447.0    NaN         NaN   NaN  2230.816086   
EnrollmentStart               14942   1490  2015-03-02    92          NaN   
EnrollmentFinish              14942   1300  2015-09-16  1684          NaN   
LastPeriodStart               14942     12  2019-07-01  3172          NaN   
LastPeriodFinish              14942     11  2019-12-31  3694          NaN   
DateLastVisit                 14942   1384  2019-10-31   475          NaN   
DaysWithoutFrequency        14942.0    NaN         NaN   NaN    81.224936   
LifetimeValue               14942.0    NaN         NaN   NaN   302.561871   
UseByTime                   14942.0    NaN         NaN   NaN     0.047116   
AthleticsActivities         14906.0    NaN         NaN   NaN      0.00738   
WaterActivities             14905.0    NaN         NaN   NaN     0.296209   
FitnessActivities           14907.0    NaN         NaN   NaN     0.576038   
DanceActivities             14906.0    NaN         NaN   NaN          0.0   
TeamActivities              14907.0    NaN         NaN   NaN     0.055544   
RacketActivities            14905.0    NaN         NaN   NaN     0.023415   
CombatActivities            14909.0    NaN         NaN   NaN     0.107921   
NatureActivities            14895.0    NaN         NaN   NaN          0.0   
SpecialActivities           14898.0    NaN         NaN   NaN     0.026514   
OtherActivities             14907.0    NaN         NaN   NaN     0.001878   
NumberOfFrequencies         14916.0    NaN         NaN   NaN    40.120542   
AttendedClasses             14942.0    NaN         NaN   NaN    10.152456   
AllowedWeeklyVisitsBySLA    14407.0    NaN         NaN   NaN     5.759561   
AllowedNumberOfVisitsBySLA  14942.0    NaN         NaN   NaN    41.636299   
RealNumberOfVisits          14942.0    NaN         NaN   NaN     5.320707   
NumberOfRenewals            14942.0    NaN         NaN   NaN      1.20526   
HasReferences               14930.0    NaN         NaN   NaN     0.019893   
NumberOfReferences          14942.0    NaN         NaN   NaN     0.022286   
Dropout                     14942.0    NaN         NaN   NaN     0.800964   

                                    std      min       25%      50%       75%  \
ID                          4313.528196  10000.0  13735.25  17470.5  21205.75   
Age                           14.156582      0.0      19.0     23.0      31.0   
Gender                              NaN      NaN       NaN      NaN       NaN   
Income                      1566.527734      0.0    1470.0   1990.0    2790.0   
EnrollmentStart                     NaN      NaN       NaN      NaN       NaN   
EnrollmentFinish                    NaN      NaN       NaN      NaN       NaN   
LastPeriodStart                     NaN      NaN       NaN      NaN       NaN   
LastPeriodFinish                    NaN      NaN       NaN      NaN       NaN   
DateLastVisit                       NaN      NaN       NaN      NaN       NaN   
DaysWithoutFrequency         144.199576      0.0      13.0     41.0     83.75   
LifetimeValue                364.319566      0.0      83.6    166.2   355.075   
UseByTime                      0.211893      0.0       0.0      0.0       0.0   
AthleticsActivities             0.08559      0.0       0.0      0.0       0.0   
WaterActivities                  0.4566      0.0       0.0      0.0       1.0   
FitnessActivities              0.494201      0.0       0.0      1.0       1.0   
DanceActivities                     0.0      0.0       0.0      0.0       0.0   
TeamActivities                 0.229047      0.0       0.0      0.0       0.0   
RacketActivities               0.151222      0.0       0.0      0.0       0.0   
CombatActivities          

#### Encoding categorical data

Dependente variables

In [24]:
# Gender - 0/1
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
gender_column = X[:, 2] # Extract the 'Male' and 'Female' column
gender_column_encoded = le.fit_transform(gender_column) # Create a LabelEncoder and fit it on the gender column
X[:, 2] = gender_column_encoded # Replace the original column
X

array([[10000, 60, 0, ..., 0, 0.0, 0],
       [10001, 29, 0, ..., 2, 0.0, 0],
       [10002, 23, 1, ..., 0, 0.0, 0],
       ...,
       [24939, 20, 1, ..., 0, 0.0, 0],
       [24940, 55, 1, ..., 2, 0.0, 0],
       [24941, 32, 0, ..., 4, 0.0, 0]], dtype=object)

In [ ]:
# Create the variable recency with EnrollmentStart; EnrollmentFinish; LastPeriodStart; LastPeriodFinish; DateLastVisit

#### Splitting the dataset into the training set and test set

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#size = 80% for training and 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1)

In [ ]:
X_train

In [ ]:
X_test

In [ ]:
y_train

In [ ]:
y_test

#### Feature Scaling

In [ ]:
# X[:, 2] gender is a dummy variable

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

In [ ]:
X_test

### Clustering

#### K-Means Clustering

In [ ]:
# comments

#### Hierarchical Clustering

In [ ]:
# comments

### Model Selection

Comment the final decision